spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users, /admin/users/**
        - id: category-service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories, /categories
        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events, /users, /events, /admin/compilations, /compilations



server:
  port: 8080

