spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users
        - id: category-service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories, /categories
        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/users/**/comments, /events/**/comments, /admin/compilations, /compilations, /admin/events,  /events, /users/**/events



server:
  port: 8080

