spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path= /admin/users, /admin/users/*, /user, /user/*
        - id: comment-service_route
          uri: lb://comment-service
          predicates:
            - Path= /users/*/events/*/comments, /users/*/events/*/comments/*, /events/*/comments, /events/*/comments/*
        - id: request-service_route
          uri: lb://request-service
          predicates:
            - Path= /users/*/requests, /users/*/requests/*/cancel, /request/event/*, /request, /request/all, /request/find
        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories, /admin/categories/*, /categories, /categories/*,   /compilations, /compilations/*, /admin/events, /admin/events/*, /users/*/events, /users/*/events/*, /users/*/events/*/requests, /events, /events/*, /users/*/requests, /users/*/requests/*/cancel, /admin/compilations, /admin/compilations/*, /compilations, /compilations/*, /event/*

server:
  port: 8080

