CREATE TABLE if not exists requests (
	status int2 NULL,
	created timestamp(6) NULL,
	event_id int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	requester_id int8 NULL,
	CONSTRAINT requests_pkey PRIMARY KEY (id),
	CONSTRAINT requests_status_check CHECK (((status >= 0) AND (status <= 3)))
);