CREATE TABLE if not exists categories (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT categories_name_key UNIQUE (name),
	CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE if not exists events (
	confirmed_requests int4 NULL,
	lat float8 NULL,
	lon float8 NULL,
	paid bool NULL,
	participant_limit int4 NULL,
	request_moderation bool NULL,
	state int2 NULL,
	category_id int8 NULL,
	create_on timestamp(6) NULL,
	event_date timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	initiator_id int8 NULL,
	published_on timestamp(6) NULL,
	rating float8 NULL,
	annotation varchar(4000) NULL,
	description varchar(7000) NULL,
	title varchar(255) NULL,
	CONSTRAINT events_pkey PRIMARY KEY (id),
	CONSTRAINT events_state_check CHECK (((state >= 0) AND (state <= 2))),
	CONSTRAINT fko6mla8j1p5bokt4dxrlmgwc28 FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE if not exists compilations (
	pinned bool NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title varchar(255) NULL,
	CONSTRAINT compilations_pkey PRIMARY KEY (id)
);

CREATE TABLE if not exists compilations_events (
	event_id int8 NOT NULL,
	id int8 NOT NULL,
	CONSTRAINT fk659jbpv3f0lpfl22817evij91 FOREIGN KEY (event_id) REFERENCES events(id),
	CONSTRAINT fko0b564ve7s4586ljcjvhoqg3h FOREIGN KEY (id) REFERENCES compilations(id)
);