spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main-service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**
            - Path=/users/**
            - Path=/events/**
            - Path=/compilations/**
            - Path=/categories/**


server:
  port: 8080
