server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ewm_event
    username: test
    password: test

grpc:
  client:
    analyzer-service: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///analyzer-service' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector-service: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///collector-service' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
