create table if not exists user_action(
    user_id int8,
    event_id int8,
    action_type varchar,
    action_time timestamp,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL
);

create table if not exists event_similarity(
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    event_a int8,
    event_b int8,
    score float8,
    event_time timestamp
);